# Generated by Django 4.2.19 on 2025-03-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_name', models.CharField(max_length=200)),
                ('productivity', models.FloatField()),
                ('quality', models.FloatField()),
                ('timeliness', models.FloatField()),
                ('prod_weight', models.FloatField(default=0.4)),
                ('qual_weight', models.FloatField(default=0.35)),
                ('time_weight', models.FloatField(default=0.25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
